version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
